### ISSUE TITLE
A question about your pre-training model

### ISSUE THREAD

**Issue by MrFeng957** [Jhaprince/MultiBully#1]
I recently read your paper and code. It seems that the code you provide needs to load the pre training model. If you want, can you upload your model and the trained model to your code base?

**Comment by Jhaprince** [comment]
Hi @MrFeng957 ,
Thanks a lot for raising your concern. Apologies for delay in response I was out of station in order to attend a conference. I will update few guidelines to run the provided code and will try to add pre-trained weights for easy reproducibility.


Regards
Prince Jha

**Comment by Jhaprince** [comment]
Hi @MrFeng957 ,
I have written the instruction to run the model in Model Training section please check back if your query gets resolved or not !
I am closing this issue now, feel free to open if you find anything doubtful
