### ISSUE TITLE
Not able to find sarcasm.py file!!!!! Please provide the entire files.

### ISSUE THREAD

**Issue by debajyotimaz** [Jhaprince/MultiBully#3]
train.py is using sarcasm module, whereas there is no sarcasm module present in the repo.

![Screenshot from 2024-03-08 12-55-49](https://github.com/Jhaprince/MultiBully/assets/65058423/e3863003-cc96-42b9-9019-f938910184cb)

**Comment by Jhaprince** [comment]
Thank you for your interest in our work!

code for sarcasm.py can be replicated with the help of sentiment.py and emotion.py, as the settings used are the same.

I hope this helps;)
