### ISSUE TITLE
Preprocessing the DAIC-WOZ dataset

### ISSUE THREAD

**Issue by ALANotFound** [Jhaprince/MultiBully#4]
Thank you for your research. I am trying to reproduce your experiment, but I have some confusion. Did you delete the questioner's voice in the data preprocessing part? Did you cut a whole speech into multiple short speeches? If you performed the speech For cutting, can you provide the relevant code?

**Comment by Jhaprince** [comment]
I guess there is some miscommunication at your end because the questions on the dataset that you are asking are in no way related to our work.

I am closing this issue from my end, feel free to reopen it in case of any queries;)
